
[main]
data_dir = "./data"


[main.http_server]
listen = ":8080"
base_url = "http://127.0.0.1:8080"


[pocket]
consumer_key = "consumer key here"
access_token = "access token here"
## Send to pocket in batch. Too many items may fail half-way due to timeout
batch = 20


[rss]
start_date = 2024-01-01T00:00:00

[rss.sources.xkcd]
name = "xkcd"
url = "https://xkcd.com/rss.xml"
# XKCD content is only one image.
# If this flag is true, it will append some text to trigger Article View in Pocket
force_article_view = true

[rss.sources.wired]
name = "Wired"
url = "https://www.wired.com/feed/rss"


[email]
server = "imap.gmail.com:993"
username = "somebody@gmail.com"
app_password = "app-specifc password"

