
[main]
data_dir = "./data"


[main.http_server]
listen = ":8080"
base_url = "http://127.0.0.1:8080"


[pocket]
consumer_key = "consumer key here"
access_token = "access token here"


[rss]
start_date = 2024-01-01T00:00:00

[rss.sources.xkcd]
name = "xkcd"
url = "https://xkcd.com/rss.xml"
use_server = true

[rss.sources.wired]
name = "Wired"
url = "https://www.wired.com/feed/rss"

